### ISSUE TITLE
Support for Nuxt 3

### ISSUE THREAD

**Issue by rvmourik** [platformsh-templates/nuxtjs#71]
### What in this template can be improved or added as a feature?

It is not this template, but there needs to be an extra template for Nuxt version 3. It was releases last month to stable channel.

I am willing to create a Pull Request but I will need a separate repo for it. 

### What exactly should be updated?

* Create a new repo for Nuxt version 3
* Build the template or let me create a PR

### How important is this feature to you?

Very important, because our newest applications are built with Nuxt version 3

### Additional context

https://nuxt.com/v3

Let me know if I can be of help.

**Comment by rvmourik** [comment]
@chadwcarlson is this something that can be done?

**Comment by schmidtsonian** [comment]
We need this please

**Comment by chadwcarlson** [comment]
Upgraded in https://github.com/platformsh-templates/nuxtjs/pull/72 @schmidtsonian @rvmourik !

**Comment by rvmourik** [comment]
Thanks @chadwcarlson
